name: Scrapping All Animes, twice time by day

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  scrapping:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.41.2-jammy

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Scrapper
        run: npm run get_all_episodes_by_anime_name
        env:
          CI: true
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SERVER_WEBHOOK: ${{ secrets.SERVER_WEBHOOK }}
          SERVER_API: ${{ secrets.SERVER_API }}
          SERVER_SECRET: ${{ secrets.SERVER_SECRET }}

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/
          retention-days: 3
